baseURL = "https://saintjosephath.github.io"
title = "Institut Saint-Joseph Ath"
publishDir = "../saintjosephath.github.io"
languageCode = "fr-be"
defaultContentLanguage = "fr"

canonifyURLs = true

disableKinds = ["RSS"]

enableRobotsTXT = true

paginate = 10
summaryLength = 64

[taxonomies]
tag = "tags"

[params]
#warning = "ceci est un message d'avertissement"
