[[document]]
name     = "Projet d'établissement"
summary  = ""
location = "docs/projet2021.pdf"
image    = "projet_etab.png"

[[document]]
name     = "Projet éducatif"
summary  = ""
location = "docs/edu2021.pdf"
image    = "projet_edu.png"

[[document]]
name     = "Projet Pédagogique"
summary  = ""
location = "docs/peda2021.pdf"
image    = "projet_peda.png"

[[document]]
name     = "Règlement des études"
summary  = ""
location = "docs/regle.pdf"
image    = "projet_regle.png"
