[[document]]
name = "maternelle"
location = "docs/mat_ath.pdf"
[[document]]
name = "1ère Primaire"
location = "docs/p1_ath.pdf"
[[document]]
name = "2ème Primaire"
location = "docs/p2_ath.pdf"
[[document]]
name = "3ème Primaire"
location = "docs/p3_ath.pdf"
[[document]]
name = "4ème primaire"
location = "docs/p4_ath.pdf"
[[document]]
name = "5ème primaire"
location = "docs/p5_ath.pdf"
[[document]]
name = "6ème primaire"
location = "docs/p6_ath.pdf"
