[[document]]
name = "accord des parents"
summary = ""
location = "docs/ACCORD_DES_PARENTS.pdf"
image = "accord_parents.png"


[[document]]
name = "fiche d'inscription"
summary = ""
location = "docs/FICHE_INSCRIPTION.pdf"
image = "fiche_inscription.png"

[[document]]
name = "paiement par application"
summary = ""
location = "docs/APSCHOOL.pdf"
image = "apschool.png"

[[document]]
name = "justificaf d'absence"
summary = ""
location = "docs/JUSTIFICATIF_ABSENCE.pdf"
image = "justificatif_absence.png"

[[document]]
name = "déclaration de protection des données personnelles"
summary = ""
location = "docs/PROTECT.pdf"
image = "rgpd.png"

[[document]]
name = "éstimation des frais pour l'année scolaire"
summary = ""
location = "docs/COST.pdf"
image = "cost.png"

[[document]]
name = "utilisation des plateformes numériques"
summary = ""
location = "docs/PLATEFORM.pdf"
image = "plateform.png"

[[document]]
name = "droit à l'image"
summary = ""
location = "docs/IMAGE.pdf"
image = "image.png"
