[[Address]]
street  = "rue des Ecriniers, 4"
zipcode = 7800
town  = "Ath"
phone = ""
image = "images/visit_ath.png"

[[Address]]
street  = "rue de Soignies, 308"
zipcode = 7810
town    = "Maffle"
phone   = ""
image = "images/visit_maffle.png"

[[Contact]]
role  = "P.O."
name  = "Xavier Muller"
phone = ""
email = "po@ceflca.be"

[[Contact]]
role  = "Direction"
name  = "Mme Vandermeets"
phone = "068/28.25.56"
email = "direction@isjam.be"

[[Contact]]
role  = "Secrétariat"
name  = "Secrétariat"
phone = "068/28.25.56"
email = "secretariat@isjam.be"

[[Contact]]
role  = "factures et service comptabilité"
name  = "Mme Céline"
phone = "0490/44.56.21"
email = "comptabilite@isjam.be"
