[[Address]]
street  = "rue des Ecriniers, 4"
zipcode = 7800
town  = "Ath"
phone = ""
image = "images/visit_ath.png"

[[Address]]
street  = "rue de Soignies, 308"
zipcode = 7810
town    = "Maffle"
phone   = ""
image = "images/visit_maffle.png"

[[Contact]]
role  = "P.O."
name  = "Mme Pillate test contact"
phone = ""
email = "institutsaintjosephath@gmail.com"

[[Contact]]
role  = "Direction"
name  = "Mme Vandermeets"
phone = "068/28.25.56"
email = "institutsaintjosephath@gmail.com"

[[Contact]]
role  = "Comptabilité"
name  = "Mme Céline"
phone = "068/28.38.47"
email = "comptabilite.elfca@gmail.com"
